import type { BlockTemplate } from './types';

export const BLOCK_TEMPLATES: BlockTemplate[] = [
  // ── Demographics ──────────────────────────────────────────────────────
  {
    blockId: 'demo_name',
    label: 'Full Name',
    description: 'Collects respondent name',
    elementType: 'short_text',
    category: 'demographics',
    tags: ['name', 'identity', 'personal'],
    defaults: { title: 'What is your full name?', required: false, placeholder: 'Jane Doe' },
  },
  {
    blockId: 'demo_email',
    label: 'Email Address',
    description: 'Collects respondent email',
    elementType: 'short_text',
    category: 'demographics',
    tags: ['email', 'contact', 'personal'],
    defaults: { title: 'What is your email address?', required: false, placeholder: 'you@example.com' },
  },
  {
    blockId: 'demo_age_range',
    label: 'Age Range',
    description: 'Age bracket selection',
    elementType: 'dropdown',
    category: 'demographics',
    tags: ['age', 'demographics', 'personal'],
    defaults: {
      title: 'What is your age range?',
      required: false,
      options: ['Under 18', '18–24', '25–34', '35–44', '45–54', '55–64', '65+'],
    },
  },
  {
    blockId: 'demo_department',
    label: 'Department',
    description: 'Work department or team',
    elementType: 'dropdown',
    category: 'demographics',
    tags: ['department', 'team', 'work', 'organization'],
    defaults: {
      title: 'Which department do you work in?',
      required: false,
      options: ['Engineering', 'Design', 'Marketing', 'Sales', 'Operations', 'HR', 'Finance', 'Other'],
    },
  },
  {
    blockId: 'demo_role',
    label: 'Job Title',
    description: 'Respondent role or position',
    elementType: 'short_text',
    category: 'demographics',
    tags: ['role', 'title', 'position', 'work'],
    defaults: { title: 'What is your job title?', required: false, placeholder: 'e.g. Product Manager' },
  },

  // ── Satisfaction & Rating ─────────────────────────────────────────────
  {
    blockId: 'nps_score',
    label: 'Net Promoter Score',
    description: 'Measures likelihood to recommend (0–10)',
    elementType: 'linear_scale',
    category: 'satisfaction',
    tags: ['nps', 'recommendation', 'loyalty', 'satisfaction'],
    defaults: {
      title: 'How likely are you to recommend us to a friend or colleague?',
      required: true,
      min: 0,
      max: 10,
      minLabel: 'Not at all likely',
      maxLabel: 'Extremely likely',
    },
  },
  {
    blockId: 'satisfaction_rating',
    label: 'Satisfaction Rating',
    description: 'Overall satisfaction on 1–5 scale',
    elementType: 'linear_scale',
    category: 'satisfaction',
    tags: ['satisfaction', 'rating', 'experience', 'overall'],
    defaults: {
      title: 'How satisfied are you overall?',
      required: true,
      min: 1,
      max: 5,
      minLabel: 'Very unsatisfied',
      maxLabel: 'Very satisfied',
    },
  },
  {
    blockId: 'likert_agreement',
    label: 'Agreement Scale',
    description: 'Likert agree/disagree choice',
    elementType: 'multiple_choice',
    category: 'satisfaction',
    tags: ['likert', 'agreement', 'opinion', 'attitude'],
    defaults: {
      title: 'To what extent do you agree with the following statement?',
      required: true,
      options: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  },
  {
    blockId: 'star_rating',
    label: 'Star Rating',
    description: 'Rate experience on 1–5 stars',
    elementType: 'linear_scale',
    category: 'satisfaction',
    tags: ['rating', 'stars', 'quality', 'experience'],
    defaults: {
      title: 'Rate your experience',
      required: true,
      min: 1,
      max: 5,
      minLabel: 'Poor',
      maxLabel: 'Excellent',
    },
  },
  {
    blockId: 'effort_score',
    label: 'Customer Effort Score',
    description: 'Measures ease of process (1–7)',
    elementType: 'linear_scale',
    category: 'satisfaction',
    tags: ['effort', 'ease', 'usability', 'ces'],
    defaults: {
      title: 'How easy was this process?',
      required: true,
      min: 1,
      max: 7,
      minLabel: 'Very difficult',
      maxLabel: 'Very easy',
    },
  },
  {
    blockId: 'quality_rating',
    label: 'Quality Rating',
    description: 'Rate quality from poor to excellent',
    elementType: 'multiple_choice',
    category: 'satisfaction',
    tags: ['quality', 'rating', 'assessment'],
    defaults: {
      title: 'How would you rate the quality?',
      required: true,
      options: ['Poor', 'Fair', 'Good', 'Very good', 'Excellent'],
    },
  },

  // ── Feedback & Open-Ended ─────────────────────────────────────────────
  {
    blockId: 'open_feedback',
    label: 'Open Feedback',
    description: 'General open-ended feedback',
    elementType: 'long_text',
    category: 'feedback',
    tags: ['feedback', 'open', 'general', 'comments'],
    defaults: {
      title: 'Is there anything else you would like to share?',
      required: false,
      placeholder: 'Share your thoughts...',
    },
  },
  {
    blockId: 'improvement_suggestion',
    label: 'Improvement Suggestion',
    description: 'What could be improved',
    elementType: 'long_text',
    category: 'feedback',
    tags: ['improvement', 'suggestion', 'constructive', 'feedback'],
    defaults: {
      title: 'What could we improve?',
      required: false,
      placeholder: 'Tell us what we could do better...',
    },
  },
  {
    blockId: 'highlight_positive',
    label: 'Positive Highlight',
    description: 'What went well',
    elementType: 'long_text',
    category: 'feedback',
    tags: ['positive', 'highlight', 'best', 'enjoy'],
    defaults: {
      title: 'What did you enjoy most?',
      required: false,
      placeholder: 'Tell us what stood out...',
    },
  },
  {
    blockId: 'short_comment',
    label: 'Brief Comment',
    description: 'Short text comment',
    elementType: 'short_text',
    category: 'feedback',
    tags: ['comment', 'brief', 'short', 'note'],
    defaults: {
      title: 'Any brief comments?',
      required: false,
      placeholder: 'Optional comment...',
    },
  },

  // ── Behavioral / Choice ───────────────────────────────────────────────
  {
    blockId: 'frequency_usage',
    label: 'Usage Frequency',
    description: 'How often something is used',
    elementType: 'multiple_choice',
    category: 'behavioral',
    tags: ['frequency', 'usage', 'how often', 'behavior'],
    defaults: {
      title: 'How often do you use this?',
      required: true,
      options: ['Daily', 'Weekly', 'Monthly', 'Rarely', 'Never'],
    },
  },
  {
    blockId: 'multiple_choice_reason',
    label: 'Reason Selection',
    description: 'Choose a primary reason',
    elementType: 'multiple_choice',
    category: 'behavioral',
    tags: ['reason', 'why', 'motivation', 'cause'],
    defaults: {
      title: 'What is your primary reason?',
      required: true,
      options: ['Option 1', 'Option 2', 'Option 3', 'Other'],
      allowOther: true,
    },
  },
  {
    blockId: 'checkbox_features',
    label: 'Feature Checklist',
    description: 'Select multiple applicable features',
    elementType: 'checkboxes',
    category: 'behavioral',
    tags: ['features', 'multi-select', 'checklist', 'options'],
    defaults: {
      title: 'Which of the following apply to you?',
      required: false,
      options: ['Feature A', 'Feature B', 'Feature C', 'Feature D'],
    },
  },
  {
    blockId: 'yes_no',
    label: 'Yes / No',
    description: 'Simple binary question',
    elementType: 'multiple_choice',
    category: 'behavioral',
    tags: ['binary', 'yes', 'no', 'boolean', 'simple'],
    defaults: {
      title: 'Do you agree?',
      required: true,
      options: ['Yes', 'No'],
    },
  },
  {
    blockId: 'preference_rank',
    label: 'Preference Selection',
    description: 'Dropdown preference choice',
    elementType: 'dropdown',
    category: 'behavioral',
    tags: ['preference', 'choice', 'select', 'rank'],
    defaults: {
      title: 'Which do you prefer?',
      required: true,
      options: ['Option A', 'Option B', 'Option C'],
    },
  },
  {
    blockId: 'contact_permission',
    label: 'Follow-up Permission',
    description: 'Ask if respondent can be contacted',
    elementType: 'multiple_choice',
    category: 'behavioral',
    tags: ['contact', 'follow-up', 'permission', 'consent'],
    defaults: {
      title: 'May we follow up with you about your responses?',
      required: false,
      options: ['Yes', 'No'],
    },
  },

  // ── Data ──────────────────────────────────────────────────────────────
  {
    blockId: 'date_picker',
    label: 'Date Selection',
    description: 'Pick a date',
    elementType: 'date',
    category: 'data',
    tags: ['date', 'when', 'schedule', 'time'],
    defaults: { title: 'Select a date', required: false },
  },
  {
    blockId: 'file_attachment',
    label: 'File Upload',
    description: 'Upload supporting files',
    elementType: 'file_upload',
    category: 'data',
    tags: ['file', 'upload', 'attachment', 'document'],
    defaults: { title: 'Upload any supporting files', required: false },
  },

  // ── Layout ────────────────────────────────────────────────────────────
  {
    blockId: 'section_intro',
    label: 'Introduction',
    description: 'Welcome section header',
    elementType: 'section_header',
    category: 'layout',
    tags: ['intro', 'welcome', 'header', 'start'],
    defaults: {
      title: 'Welcome',
      description: 'Thank you for taking the time to complete this survey. Your feedback is valuable.',
      required: false,
    },
  },
  {
    blockId: 'section_divider',
    label: 'Section Divider',
    description: 'Divides survey into sections',
    elementType: 'section_header',
    category: 'layout',
    tags: ['section', 'divider', 'break', 'group'],
    defaults: { title: 'Section Title', description: '', required: false },
  },
  {
    blockId: 'page_separator',
    label: 'Page Break',
    description: 'Starts a new page',
    elementType: 'page_break',
    category: 'layout',
    tags: ['page', 'break', 'next', 'separator'],
    defaults: { title: 'Page Break', required: false },
  },
];

/** Look up a block template by its ID. */
export function getBlockTemplate(blockId: string): BlockTemplate | undefined {
  return BLOCK_TEMPLATES.find((b) => b.blockId === blockId);
}
