import type { SurveyTemplate } from './types';

export const SURVEY_TEMPLATES: SurveyTemplate[] = [
  {
    templateId: 'customer_satisfaction',
    label: 'Customer Satisfaction',
    description: 'Measure customer happiness across touchpoints',
    category: 'customer',
    icon: 'Smile',
    estimatedTime: '3–5 min',
    blocks: [
      { blockId: 'section_intro', overrides: { title: 'Customer Feedback', description: 'We value your opinion. This survey takes about 3 minutes.' } },
      { blockId: 'nps_score' },
      { blockId: 'satisfaction_rating' },
      { blockId: 'quality_rating' },
      { blockId: 'improvement_suggestion' },
      { blockId: 'open_feedback' },
      { blockId: 'contact_permission' },
    ],
  },
  {
    templateId: 'employee_engagement',
    label: 'Employee Engagement',
    description: 'Assess team morale, satisfaction, and culture',
    category: 'employee',
    icon: 'Users',
    estimatedTime: '5–8 min',
    blocks: [
      { blockId: 'section_intro', overrides: { title: 'Employee Engagement Survey', description: 'Your honest feedback helps us build a better workplace.' } },
      { blockId: 'demo_department' },
      { blockId: 'likert_agreement', overrides: { title: 'I feel valued and recognized for my contributions.' } },
      { blockId: 'likert_agreement', overrides: { title: 'I have the resources I need to do my job effectively.' } },
      { blockId: 'likert_agreement', overrides: { title: 'I would recommend this company as a great place to work.' } },
      { blockId: 'satisfaction_rating', overrides: { title: 'How satisfied are you with your work-life balance?' } },
      { blockId: 'improvement_suggestion', overrides: { title: 'What is one thing we could do to improve your work experience?' } },
      { blockId: 'open_feedback' },
    ],
  },
  {
    templateId: 'event_feedback',
    label: 'Event Feedback',
    description: 'Collect feedback after events, workshops, or conferences',
    category: 'event',
    icon: 'Calendar',
    estimatedTime: '3–5 min',
    blocks: [
      { blockId: 'section_intro', overrides: { title: 'Event Feedback', description: 'Thank you for attending! Help us make future events even better.' } },
      { blockId: 'star_rating', overrides: { title: 'How would you rate the event overall?' } },
      { blockId: 'checkbox_features', overrides: { title: 'Which aspects did you enjoy?', options: ['Speakers', 'Networking', 'Content quality', 'Venue', 'Catering', 'Organization'] } },
      { blockId: 'highlight_positive', overrides: { title: 'What was the highlight of the event?' } },
      { blockId: 'improvement_suggestion', overrides: { title: 'How could future events be improved?' } },
      { blockId: 'yes_no', overrides: { title: 'Would you attend a similar event in the future?' } },
      { blockId: 'contact_permission' },
    ],
  },
  {
    templateId: 'product_feedback',
    label: 'Product Feedback',
    description: 'Gather insights on product usage and satisfaction',
    category: 'product',
    icon: 'Package',
    estimatedTime: '4–6 min',
    blocks: [
      { blockId: 'section_intro', overrides: { title: 'Product Feedback', description: 'Help us understand how you use our product and where we can improve.' } },
      { blockId: 'frequency_usage' },
      { blockId: 'satisfaction_rating', overrides: { title: 'How satisfied are you with the product?' } },
      { blockId: 'effort_score', overrides: { title: 'How easy is the product to use?' } },
      { blockId: 'checkbox_features', overrides: { title: 'Which features do you use most?', options: ['Feature A', 'Feature B', 'Feature C', 'Feature D', 'Feature E'] } },
      { blockId: 'improvement_suggestion', overrides: { title: 'What feature would you most like to see added or improved?' } },
      { blockId: 'nps_score' },
    ],
  },
  {
    templateId: 'market_research',
    label: 'Market Research',
    description: 'Understand your target audience and market',
    category: 'research',
    icon: 'Search',
    estimatedTime: '5–8 min',
    blocks: [
      { blockId: 'section_intro', overrides: { title: 'Market Research Survey', description: 'Help us understand your needs and preferences.' } },
      { blockId: 'demo_age_range' },
      { blockId: 'demo_role' },
      { blockId: 'multiple_choice_reason', overrides: { title: 'How did you first hear about us?', options: ['Search engine', 'Social media', 'Word of mouth', 'Advertisement', 'Other'] } },
      { blockId: 'frequency_usage', overrides: { title: 'How often do you use products like ours?' } },
      { blockId: 'checkbox_features', overrides: { title: 'What factors are most important when choosing a product like ours?', options: ['Price', 'Quality', 'Brand reputation', 'Features', 'Customer support', 'Ease of use'] } },
      { blockId: 'preference_rank', overrides: { title: 'Which competitor product do you currently use?', options: ['Competitor A', 'Competitor B', 'Competitor C', 'None'] } },
      { blockId: 'open_feedback', overrides: { title: 'What unmet needs do you have in this space?' } },
    ],
  },
  {
    templateId: 'training_evaluation',
    label: 'Training Evaluation',
    description: 'Evaluate training sessions and courses',
    category: 'employee',
    icon: 'GraduationCap',
    estimatedTime: '3–5 min',
    blocks: [
      { blockId: 'section_intro', overrides: { title: 'Training Evaluation', description: 'Please share your feedback on the training session.' } },
      { blockId: 'star_rating', overrides: { title: 'How would you rate the training overall?' } },
      { blockId: 'likert_agreement', overrides: { title: 'The training content was relevant to my role.' } },
      { blockId: 'likert_agreement', overrides: { title: 'The instructor was knowledgeable and engaging.' } },
      { blockId: 'quality_rating', overrides: { title: 'How would you rate the training materials?' } },
      { blockId: 'improvement_suggestion', overrides: { title: 'How could this training be improved?' } },
      { blockId: 'yes_no', overrides: { title: 'Would you recommend this training to a colleague?' } },
    ],
  },
  {
    templateId: 'website_usability',
    label: 'Website Usability',
    description: 'Evaluate website user experience',
    category: 'product',
    icon: 'Globe',
    estimatedTime: '3–5 min',
    blocks: [
      { blockId: 'section_intro', overrides: { title: 'Website Feedback', description: 'Help us improve your experience on our website.' } },
      { blockId: 'effort_score', overrides: { title: 'How easy was it to find what you were looking for?' } },
      { blockId: 'satisfaction_rating', overrides: { title: 'How satisfied are you with the website design?' } },
      { blockId: 'multiple_choice_reason', overrides: { title: 'What was the purpose of your visit?', options: ['Browse products', 'Make a purchase', 'Get support', 'Learn more about us', 'Other'] } },
      { blockId: 'checkbox_features', overrides: { title: 'Which areas need improvement?', options: ['Navigation', 'Search', 'Page speed', 'Mobile experience', 'Content clarity', 'Visual design'] } },
      { blockId: 'improvement_suggestion' },
    ],
  },
  {
    templateId: 'exit_interview',
    label: 'Exit Interview',
    description: 'Understand why employees are leaving',
    category: 'employee',
    icon: 'DoorOpen',
    estimatedTime: '5–8 min',
    blocks: [
      { blockId: 'section_intro', overrides: { title: 'Exit Interview', description: 'Your candid feedback will help us improve the employee experience.' } },
      { blockId: 'demo_department' },
      { blockId: 'multiple_choice_reason', overrides: { title: 'What is the primary reason you are leaving?', options: ['Career growth', 'Compensation', 'Work-life balance', 'Management', 'Company culture', 'Relocation', 'Other'] } },
      { blockId: 'likert_agreement', overrides: { title: 'I felt supported by my direct manager.' } },
      { blockId: 'likert_agreement', overrides: { title: 'I had opportunities for professional growth.' } },
      { blockId: 'satisfaction_rating', overrides: { title: 'How satisfied were you with your overall experience at the company?' } },
      { blockId: 'improvement_suggestion', overrides: { title: 'What is one thing the company could have done differently to retain you?' } },
      { blockId: 'open_feedback' },
    ],
  },
  {
    templateId: 'general_feedback',
    label: 'General Feedback',
    description: 'Simple general-purpose feedback form',
    category: 'general',
    icon: 'MessageSquare',
    estimatedTime: '2–3 min',
    blocks: [
      { blockId: 'section_intro' },
      { blockId: 'satisfaction_rating' },
      { blockId: 'open_feedback' },
      { blockId: 'contact_permission' },
    ],
  },
  {
    templateId: 'blank',
    label: 'Blank Survey',
    description: 'Start from scratch with an empty canvas',
    category: 'general',
    icon: 'Plus',
    estimatedTime: '—',
    blocks: [],
  },
];

/** Look up a survey template by its ID. */
export function getSurveyTemplate(templateId: string): SurveyTemplate | undefined {
  return SURVEY_TEMPLATES.find((t) => t.templateId === templateId);
}
